Hw04 auth
nelli-belovol/nodejs-homework-rest-api pull request #3
Opened 2022-02-05 15:34 UTC by nelli-belovol

add 4 Homework

2022-02-05 19:17 UTC, KirillKulakow commented on middlewares/authenticate.js
> +    const [bearer, token] = authorization.split(" ");
если authorization будет undefined -> будет ошибка и сломается приложение

2022-02-05 19:20 UTC, KirillKulakow commented on routes/api/contacts.js
> +    const skip = (page - 1) * limit;
рекомендую перед математическими вычислениями проверять входящие параметры, например через isNaN на тот факт что внутрь приходит именно число (строка число или число число)

2022-02-05 19:21 UTC, KirillKulakow commented on routes/api/contacts.js
>  router.get("/:contactId", async (req, res, next) => {
не хватает прослойки аутентификации + не хватает логики конфиденциальности контактов
другой пользователь сможет увидеть твой контакт

2022-02-05 19:21 UTC, KirillKulakow commented on routes/api/contacts.js
> +    console.log(data);
удалить

2022-02-05 19:25 UTC, KirillKulakow commented on routes/api/contacts.js
>  router.get("/:contactId", async (req, res, next) => {
тоже самое с удалением и изменением контакта

2022-02-05 19:28 UTC, KirillKulakow commented on routes/api/contacts.js
> +router.get("/:contactId/favorite", authenticate, async (req, res, next) => {
лучше перенести эту логику в 10 строку
по типу - req.query будет принимать параметр favorite или yes или no
если yes будет поиск по favorite true
если no будет поиск по favorite false
если в req.query - параметр favorite отутствует тогда этот параметр не учитывается в поиске

2022-02-05 19:30 UTC, KirillKulakow requested changes
Need fix

2022-02-05 20:28 UTC, nelli-belovol commented on routes/api/contacts.js
> +    const skip = (page - 1) * limit;
для этого потом внутрь result пишем +limit, чтобы входящая строка становилась числовым значением

2022-02-05 21:17 UTC, KirillKulakow commented on routes/api/contacts.js
> +    const skip = (page - 1) * limit;
а если кто то случайно в page напишет например one)

2022-02-05 22:18 UTC, KirillKulakow commented on routes/api/contacts.js
> +    if (favorite) {
1) все что приходит в query это строка и только строка
2) у тебя очень много дублирования кода и по факту у тебя меняется только пара составляющих
3) у тебя должно быть несколько проверок
- проверка favorite
`if (favorite && !["yes", "no"].includes(favorite)) throw badRequest`
- составной фильтр
```
const filter = { owner: _id }
if (favorite) filter.favorite = favorite === "yes"
```
дальше твой стандартний поиск с этим фильтром

2022-02-05 22:19 UTC, KirillKulakow commented on routes/api/contacts.js
> +        {
насколько я помню у данного метода третим параметром идут опции и я не помню чтобы в опциях был параметр favorite

2022-02-05 22:19 UTC, KirillKulakow commented on routes/api/contacts.js
> +        {
https://mongoosejs.com/docs/api.html#model_Model.find

2022-02-05 22:21 UTC, KirillKulakow commented on routes/api/contacts.js
>  router.get("/:contactId", async (req, res, next) => {
не хватает логики конфиденциальности контактов
другой пользователь сможет увидеть/изменить и даже удалить твой контакт
если не понятно то что я пишу - я есть в слаке и могу помочь

2022-02-05 22:22 UTC, KirillKulakow requested changes
Need fix

2022-02-08 20:41 UTC, KirillKulakow commented
Еще один момент упущен
Ты сделала аутентификацию но при этом любой юзер может смотреть/удалять/изменять любой контакт (свой и не свой)
нужна сделать поиск по всем роутам не только по ид контакта но и по ид собственника

2022-02-08 20:44 UTC, KirillKulakow requested changes
Need fix one comment

2022-02-08 21:21 UTC, KirillKulakow approved these changes

2022-02-08 21:22 UTC, merged